version: '3'

networks:
  react_net:
    driver: bridge

services:
  front:
    build: ./
    image: react00
    container_name: front
    tty: true
    volumes:
      - ../app:/app
    working_dir: "/app"
    ports:
      - 8000:8000
    networks:
      - react_net